[tool.poetry]
name = "balena-hal"
version = "0.1.0"
description = ""
authors = ["Rahul Thakoor <rahul@balena.io>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
